### ISSUE TITLE
typechain/ethers is missing when launching the mono

### ISSUE THREAD

**Issue by NedimRenesalis** [goldfinch-eng/mono#13]
in

https://github.com/goldfinch-eng/mono

I go:

npm install
npm run bootstrap

and this error comes out:

GOLDFINCH/mono/packages/server/node_modules/ts-node/src/index.ts:692
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
../autotasks/index.ts(10,30): error TS2307: Cannot find module '@goldfinch-eng/protocol/typechain/ethers' or its corresponding type declarations.

is ethers the npm ethers package? if so, I tried installing it and it says I dont have permissions.

any ideas how to work around here?

**Comment by NedimRenesalis** [comment]
No one to answer this one?

**Comment by wbj-goldfinch** [comment]
Hi @NedimRenesalis,

Can you let me know what version of node you're attempting this with?

I was able to successfully bootstrap the repo using

```
npm install
npm run bootstrap
```

using **node 12.18.3**

**Comment by wbj-goldfinch** [comment]
Hi @NedimRenesalis, since #14 was resolved successfully and this was a predecessor to that issue, I'm going to close this out as well.

Glad you were able to get it working
