### ISSUE TITLE
Error when starting /mono ----> "Failed at the @goldfinch-eng/protocol@0.1.0 start script."

### ISSUE THREAD

**Issue by NedimRenesalis** [goldfinch-eng/mono#14]
I run

```
npm install
npm run bootstrap
```

and then I run

```
npm run start
```
and this error is the output

<img width="942" alt="Screenshot 2022-04-14 012959" src="https://user-images.githubusercontent.com/19872990/163288254-586011ee-02d0-4da2-a828-c4666ec44901.png">

**Comment by wbj-goldfinch** [comment]
Hi @NedimRenesalis, looking around it appears that exit code `137` means that the process ran out of memory. Can you post your system specs?

**Comment by wbj-goldfinch** [comment]
Is this a follow up issue after using node 12.183 #13?

**Comment by NedimRenesalis** [comment]
> Is this a follow up issue after using node 12.183 #13?

Yes.

**Comment by NedimRenesalis** [comment]
It worked.

Thank you

**Comment by NedimRenesalis** [comment]
.
