### ISSUE TITLE
Instructions missing - the project cannot be run 

### ISSUE THREAD

**Issue by ctindogaru** [goldfinch-eng/mono#17]
Hello,

First of all, congrats for the amazing effort put into this repo.

I've tried to run the project, but it doesn't seem to be working. I'm getting the same errors over and over again.

When running `npm run start:local`, I get:
```
Unhandled Rejection (Error): You must provide the json interface of the contract when instantiating a contract object.
▶ 3 stack frames were collapsed.
GoldfinchProtocol.getContract
src/ethereum/GoldfinchProtocol.ts:71
  68 | } else {
  69 |   abi = contractOrAbi
  70 | }
> 71 | const readOnly = new web3.readOnly.eth.Contract(abi, address) as unknown as T
     | ^  72 | ;(readOnly as any).loaded = true
  73 | const userWallet = new web3.userWallet.eth.Contract(abi, address) as unknown as T
  74 | ;(userWallet as any).loaded = true
```

When running `start:local:liquidity-mining`, I get:
```
Unhandled Rejection (Error): MerkleDirectDistributor address of GFI contract doesn't match with deployed GFI address
MerkleDirectDistributor._callee$
src/ethereum/merkleDirectDistributor.ts:35
  32 |   }
  33 | }
  34 | 
> 35 | async initialize(currentBlock: BlockInfo): Promise<void> {
     | ^  36 |   const [gfiAddress, isPaused] = await Promise.all([
  37 |     this.contract.readOnly.methods.gfi().call(undefined, currentBlock.number),
  38 |     this.contract.readOnly.methods.paused().call(undefined, currentBlock.number),
```

Note that the second command was running fine before the last changes in May got pushed.

Can I please get some help here? Are there any additional steps that need to be taken in order to be able to run the project?

**Comment by ctindogaru** [comment]
It would be amazing if other folks can help you building on your product. But to be able to help, we need to be able to run the project first :D

**Comment by ihinsdale** [comment]
@ctindogaru Thanks for opening this issue!

In regards to your error running `npm run start:local`, can you confirm that you ran `npm run bootstrap` first?

In regards to your error running `npm start:local:liquidity-mining`, can you confirm that in the browser, your Metamask extension is pointing against localhost (and therefore *not* mainnet)? Your localhost network in Metamask needs to be configured with RPC url `http://localhost:8545` to communicate with the local hardhat node, and its chain id needs to be `31337`.

**Comment by ctindogaru** [comment]
The recommendation for `npm start:local:liquidity-mining ` fixed the issue. Thank you so much!

However, when running `npm run start:local `, I'm still running into the same issue. On what network should I be when running `npm run start:local`? `http://localhost:8545` with chain id 31337 right?

**Comment by ihinsdale** [comment]
> On what network should I be when running npm run start:local? http://localhost:8545 with chain id 31337 right?

That's right. The `npm start:local*` commands run a local blockchain via hardhat, so you want your Metamask to point to that chain.

I have sometimes observed weird behavior like that `Unhandled Rejection (Error): You must provide the json interface of the contract when instantiating a contract object.` error if I have multiple Goldfinch tabs open at once, where one is for `https://app.goldfinch.finance` which needs Metamask to point to mainnet, and one is for `http://localhost:3000` which needs Metamask to point to localhost. In that situation, it seemed like even if `http://localhost:3000` was the active tab, I would have trouble switching Metamask to localhost, as if Metamask was trying to give priority to mainnet for `https://app.goldfinch.finance`. That problem would go away by closing the `https://app.goldfinch.finance` tab.

The `Unhandled Rejection (Error): You must provide the json interface...` error itself though sounds like the client JS is not obtaining the ABI json that it needs. When running locally, this ABI json comes from `packages/protocol/deployments/all_dev.json`. It is loaded by the client in `getDeployments()` in `packages/client/src/ethereum/utils.ts`.

Unfortunately I'm not able to debug this myself at the moment, as the repo HEAD runs on node v14, and I'm on an M1 Macbook Pro which needs node v16. If you are still stuck with `npm run start:local`, I can ask a team member to continue debugging. 

But if `npm run start:local:liquidity-mining` works for you, you should just keep using that, as it provides a superset of the functionality of `npm run start:local` (specifically, it just also makes your `TEST_USER` address the recipient of some `Merkle*Distributor` grants).

**Comment by ctindogaru** [comment]
> Unfortunately I'm not able to debug this myself at the moment, as the repo HEAD runs on node v14, and I'm on an M1 Macbook Pro which needs node v16. If you are still stuck with npm run start:local, I can ask a team member to continue debugging.

Same here, but using M1 with node v14 works as well.

> I can ask a team member to continue debugging.

Yes please, I would appreciate that!

> But if npm run start:local:liquidity-mining works for you, you should just keep using that, as it provides a superset of the functionality of npm run start:local 

So start:local:liquidity-mining = start:local + more ?

**Comment by ihinsdale** [comment]
> start:local:liquidity-mining = start:local + more

Yes!

> Yes please, I would appreciate that!

 I've pinged Warbler's on-call engineer about trying to repro.

**Comment by wbj-goldfinch** [comment]
Hey @ctindogaru are you still encountering this issue?

**Comment by ctindogaru** [comment]
We can close this for now, I've focused on smart contracts lately so didn't run into this issue anymore.
