### ISSUE TITLE
Infinite loading when installing the project

### ISSUE THREAD

**Issue by ctindogaru** [goldfinch-eng/mono#28]
I have an Apple M1 Pro chipset and tried to compile the entire the project multiple times. The project does not seem to finish compiling, it seems that the installation just hangs after some point.

This didn't happen prior to the latest merge.

Command that's causing the issue: `npm run bootstrap`.

PR that seems to have caused the issue: https://github.com/goldfinch-eng/mono/pull/27

**Comment by gregegan** [comment]
Did you try wiping all your node modules? I think there is also a `npx lerna clean` command you can try

**Comment by bstchow** [comment]
Hi @ctindogaru - I was able to run `npm install` -> `npm run bootstrap` after pulling down the repo into a fresh directory. I think Greg's recommendations would be a good start

**Comment by ctindogaru** [comment]
worked this time, I'm not sure what was wrong with the previous runs. I was running it on a fresh clone each time...

Thanks guys!
