### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by kabir-kapur** [goldfinch-eng/mono#42]
Is development in this repo still happening? Seems there haven't been any new merges for a couple month.

**Comment by kartikdangi** [comment]
I am looking for the same query whether there is still ongoing development

**Comment by blakewest** [comment]
yeah totally, there is! New stuff should be getting merged soon.

**Comment by bstchow** [comment]
@kabir-kapur @kartikdangi We just merged in some of the latest updates to the protocol! Enjoy~
